apiVersion: v1
kind: ServiceAccount
metadata:
  name: inkwell
  namespace: inkwell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inkwell
  namespace: inkwell
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: inkwell
  template:
    metadata:
      labels:
        app: inkwell
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: inkwell
        vault.hashicorp.com/agent-inject-secret-app.env: secret/data/inkwell/config
        vault.hashicorp.com/agent-inject-template-app.env: |
          {{- with secret "secret/data/inkwell/config" -}}
          DATABASE_URL={{ .Data.data.DATABASE_URL }}
          DATABASE_SSL={{ .Data.data.DATABASE_SSL }}
          {{- end }}
    spec:
      serviceAccountName: inkwell
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: inkwell-blog:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: DOTENV_CONFIG_PATH
              value: /vault/secrets/app.env
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: inkwell
  namespace: inkwell
spec:
  selector:
    app: inkwell
  ports:
    - name: http
      port: 80
      targetPort: http
