const database = require('./client');

async function migrate() {
  await database.query(`
    CREATE TABLE IF NOT EXISTS authors (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      role TEXT NOT NULL,
      avatar_url TEXT NOT NULL,
      bio TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      slug TEXT NOT NULL UNIQUE,
      color TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS posts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      excerpt TEXT NOT NULL,
      content TEXT NOT NULL,
      image_url TEXT NOT NULL,
      published_at DATE NOT NULL,
      read_minutes INTEGER NOT NULL DEFAULT 5 CHECK(read_minutes > 0),
      featured BOOLEAN NOT NULL DEFAULT FALSE,
      author_id INTEGER NOT NULL REFERENCES authors(id) ON DELETE RESTRICT,
      category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_posts_published_at ON posts(published_at DESC);
    CREATE INDEX IF NOT EXISTS idx_posts_category_id ON posts(category_id);
    CREATE INDEX IF NOT EXISTS idx_posts_featured ON posts(featured);
  `);
}

module.exports = migrate;
